#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 19 21:18:21 2017

@author: NNK
@title: Analysis of Investment Vehicles in Python
"""

#%matplotlib inline
import pandas as pd
import pandas_datareader.data as web
import datetime
import seaborn as sb
import sklearn.linear_model as lm
from sklearn.model_selection import train_test_split
import sklearn as sk
sb.set_style("whitegrid")

start = datetime.datetime(2014,1,1)
end = datetime.datetime.today()
NVDA = web.DataReader("NVDA", 'google', start, end)

NVDA.head()
NVDA.tail()

NVDA = pd.DataFrame(NVDA)
